footprint: [[0.55, 0.4], [-0.55, 0.4], [-0.55, -0.4], [0.55, -0.4]]
#robot_radius: 0.5            # 机器人半径
footprint_padding: 0.05       # footprint膨胀系数

obstacle_range: 10.0          # 障碍物探测距离
raytrace_range: 6.0           # 除指定范围外的空间

resolution: 0.05              # 地图分辨率

inflation_radius: 1.0         # 膨胀半径
#max_obstacle_height: 0.6     # 最大障碍物高度
#min_obstacle_height: 0.0     # 最小障碍物高度

observation_sources: laser    # 观察源 laser或point_cloud_sensor:
laser: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}  # 观察源的数据类型
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}