DWAPlannerROS:
  acc_lim_x: 1.5                  # x方向的加速度极限，单位为 meters/sec^2 (double, default: 2.5)
  acc_lim_y: 0.0                  # x方向的加速度极限，单位为 meters/sec^2 (double, default: 2.5)
  acc_lim_th: 1.5                 # 角加速度极限，单位为 radians/sec^2 (double, default: 3.2)

# The velocity when robot is moving in a straight line
  max_vel_trans: 0.8             # 机器人最大平移速度的绝对值 (double, default: 0.55)
  min_vel_trans: 0.1             #                       (double, default: 0.1)
  max_vel_theta: 1.0             # 最大角速度的绝对值，单位为 rad/s (double, default: 1.0)
  min_vel_theta: 0.2             #                             (double, default: 0.4)

# Robot Configuration Parameters
  max_vel_x: 0.8                 # 机器人在x方向的速度极限，单位为 meters/sec^2 (double, default: 0.55)
  min_vel_x: 0.0                 #                                        (double, default: 0.0)

  max_vel_y: 0.0                 #                                         (double, default: 0.1)
  min_vel_y: 0.0                 #                                         (double, default: -0.1)

# Goal Tolerance Parametes 
  yaw_goal_tolerance: 0.05      # (double, default: 0.05)
  xy_goal_tolerance: 0.1        # (double, default: 0.10)
  latch_xy_goal_tolerance: true # 如果锁定目标公差且机器人到达目标xy位置，机器人将简单地旋转到位，即使它在目标公差的范围内结束 (bool, default: false)
# Forward Simulation Parameters
  sim_time: 1.5                 # 给定轨迹上的点之间的间隔尺寸，单位为 meters (double, default: 1.7)
  sim_granularity: 0.025        # (double, default: 0.025)
  vx_samples: 20                # 样本数 (integer, default: 3)
  vy_samples: 0                 # (integer, default: 10)
  vth_samples: 20               # 角速度的样本数 (integer, default: 20)
  controller_frequency: 5.0     # 调用该控制器的频率 (double, default: 20.0)

# Trajectory Scoring Parameters
  path_distance_bias: 32.0      # 控制器靠近给定路径的权重 (double, default: 32.0)
  goal_distance_bias: 24.0      # 控制器尝试达到其本地目标and控制着速度的权重。(double, default: 24.0)
  occdist_scale: 0.05           # 控制器尝试避免障碍物的权重 (double, default: 0.01)
  forward_point_distance: 0.325 # 从机器人中心点到另一个得分点的距离 (double, default: 0.325)
  stop_time_buffer: 0.1         # 机器人在碰撞前必须停止的时间 (double, default: 0.2)
  scaling_speed: 0.25           # 缩放机器人足迹的速度的绝对值，单位为m/s (double, default: 0.25)
  max_scaling_factor: 0.2       # 缩放机器人足迹的最大因子 (double, default: 0.2)
  publish_cost_grid: false      # (bool, default: false)

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # 机器人必须运动多少米远后才能复位震荡标记 (double, default: 0.05)

# Debugging
  publish_traj_pc : true        # 将规划的轨迹在RVIZ上进行可视化
  publish_cost_grid_pc: true    # 将代价值进行可视化显示 (bool, default: false)
  #是否发布规划器在规划路径时的代价网格.如果设置为true,那么就会在~/cost_cloud话题上发布sensor_msgs/PointCloud2类型消息

