global_costmap:
  global_frame: map                   # 使用map框架作为global框架
  robot_base_frame: base_footprint    # 机器人最底层框架
  update_frequency: 5.0               # 全局地图更新频率，1.0~5.0
  update_frequency: 10.0              # 发布频率
  transform_tolerance: 0.55
  resolution: 0.05                    # 地图分辨率
  static_map: true                    # 是否为静态地图，一般为静态
  rolling_window: false               # 更新全局地图
