shutdown_costmaps: false      # 当move_base进入inactive状态时候，决定是否停用节点的costmap (bool, default: false)
controller_frequency: 20.0    # 以Hz为单位的速率运行控制循环并向基座发送速度命令 (double, default: 20.0)
planner_patience: 5.0         # 在空间清理操作执行前，路径规划器等待多长时间（秒）用来找出一个有效规划 (double, default: 5.0)
controller_patience: 15.0     # 在空间清理操作执行前，控制器会等待多长时间（秒）用来找出一个有效控制  (double, default: 15.0)
conservative_reset_dist: 5.0  # 当在地图中清理出空间时候，距离机器人几米远的障碍将会从costmap清除  (double, default: 3.0)
planner_frequency: 5.0        # 全局路径规划器loop速率 (double, default: 0.0)
oscillation_timeout: 10.0     # 执行修复操作之前，允许的震荡时间是几秒  (double, default: 0.0)
oscillation_distance: 0.3     # 机器人需要移动多少距离才算作没有震荡 (double, default: 0.5)
max_planning_retries: 50
recovery_behavior_enabled: false    # 复原行为使能
clearing_rotation_allowed: false    # 清除旋转允许
